site_name: AWS Studies
repo_url: https://github.com/jbcodeforce/aws-studies.git
nav:
  - Introduction: index.md
  - Infrastructure: 
      - EC2-ASG: infra/index.md
      - Network: infra/networking.md
      - Security: infra/security.md
      - S3-Storage: infra/storage.md
      - Route 53: infra/route53.md
      - Monitoring: monitoring/monitoring.md
      - Messaging: infra/messaging.md
      - Streams-Firehose: kinesis/index.md
  - Architecture:
      - Well Architectured: sa/well-architectured.md
      - Solution design: sa/sol-design.md
      - SA: sa/psa-role.md
      - SaaS: sa/saas.md
      - Resilience: sa/resilience.md
      - Conduct Design session: templ/index.md
  - Analytics: analytics/index.md
  - Data:
      - RDS-Aurora-ES: data/index.md
      - DynamoDB: data/dynamodb.md
      - Data Lake: data/data-lake.md
      - RedShift: data/redshift.md
  - AI-ML: ai-ml/index.md
  - Serverless:
      - Introduction: serverless/index.md
      - Lambda: serverless/lambda.md
      - EKS: serverless/eks.md
      - EventBridge: serverless/eventbridge.md
  - Playground: 
      - Getting Started IAM-EC2: playground/gettingstarted.md
      - RDS: playground/rds.md
      - Data processing: playground/rt-data-processing.md
      - Analytics on EMR: playground/spark-emr.md
      - ECS: playground/ecs.md
  - Coding:
      - Practices: coding/index.md
      - CloudFormation: coding/cloudFormation.md
      - CDK: coding/cdk.md
  - Return to main: https://jbcodeforce.github.io
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top

  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true