site_name: AWS Studies
repo_url: https://github.com/jbcodeforce/aws-studies.git
nav:
  - Introduction: index.md
  - Infrastructure: 
      - Introduction: infra/index.md
      - Storage: infra/storage.md
  - Playground: playground/gettingstarted.md
  - Solution architecture:
      - Well Architectured: sa/well-architectured.md
      - Solution design: sa/sol-design.md
      - SA: sa/psa-role.md
  - Serverless:
      - Introduction: serverless/index.md
      - Lambda: serverless/lambda.md
  - Data:
      - Data services: data/index.md
  - Coding:
      - CDK: coding/cdk.md
  - Return to main: https://jbcodeforce.github.io
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      #- navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'twitter'
      link: 'https://twitter.com/agileitarch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details